name = "endcity-playercount"
main = "playercount-worker.js"
compatibility_date = "2026-04-14"

[triggers]
crons = ["*/2 * * * *"]

[[d1_databases]]
binding = "PLAYERCOUNT_DB"
database_name = "endcity-playercount"
database_id = "c6113ed5-4c17-4f04-aaf2-b435b3417d58"
